# Generated by Django 2.1.2 on 2018-11-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='enable',
        ),
        migrations.AddField(
            model_name='blog',
            name='enable',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
