# Generated by Django 2.1.2 on 2018-11-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='captcha',
            field=models.CharField(default=1234, max_length=8, verbose_name='验证码'),
            preserve_default=False,
        ),
    ]
