# Generated by Django 2.1.2 on 2018-11-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181109_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='captcha',
            field=models.CharField(max_length=8, verbose_name='验证码'),
        ),
    ]
