# Generated by Django 2.1.2 on 2018-11-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181109_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='captcha',
            field=models.CharField(default=1, max_length=8, verbose_name='验证码'),
            preserve_default=False,
        ),
    ]
